In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
a=np.array(60)
print(a)
print(type(a))
print(a.ndim)

60
<class 'numpy.ndarray'>
0


In [7]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)


[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [9]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(type(d))
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [10]:
arr=np.array([1,2,3,4,5])
print(arr+10)
print(arr.mean())
print(arr.shape)

[11 12 13 14 15]
3.0
(5,)
